// Auto-generated by index.html – nicht von Hand editieren.
window.KLAUSUR_DATA = {
  "topics": [
    {
      "title": "SWOT-Analyse",
      "location": "Satz 1, S. 86",
      "notes": "",
      "attachments": [
        {
          "id": "4eols6ix4jav",
          "name": "SWOT-Analyse erklärt.m4a",
          "path": "notes/SWOT-Analyse erklärt.m4a",
          "source": "repo"
        }
      ],
      "id": "imc4ee9j3rto",
      "cards": [
        {
          "id": "bwxw91my3zos",
          "front": "testkarte",
          "back": "tsdkgnsg"
        }
      ]
    },
    {
      "title": "Nutzwertanalyse",
      "location": "Satz 1, S. 99",
      "notes": "",
      "attachments": [
        {
          "id": "6uzpehsaxt16",
          "name": "Nutzwertanalyse erklärt.m4a",
          "path": "notes/Nutzwertanalyse erklärt.m4a",
          "source": "repo"
        }
      ],
      "id": "jsgiw7sz3rto",
      "cards": []
    },
    {
      "title": "Rechtsformen",
      "location": "Satz 1, S. 109",
      "notes": "",
      "attachments": [],
      "id": "cijrjc8g3rto",
      "cards": [
        {
          "id": "rf01",
          "front": "Was ist eine Rechtsform?",
          "back": "Das juristische Kleid einer Wirtschaftseinheit — alle Regelungen, die einen Betrieb zu einer rechtlich fassbaren Einheit machen. Geregelt in BGB, HGB, GmbHG, AktG und GenG."
        },
        {
          "id": "rf02",
          "front": "Was ist der Unterschied zwischen Personengesellschaften und Kapitalgesellschaften?",
          "back": "Personengesellschaften: keine eigene Rechtspersönlichkeit, Gesellschafter haften persönlich.\nKapitalgesellschaften: juristische Person mit eigener Rechtspersönlichkeit, Haftung nur mit Gesellschaftsvermögen."
        },
        {
          "id": "rf03",
          "front": "Nenne alle Personengesellschaften.",
          "back": "Einzelunternehmung, GbR, OHG, KG, Stille Gesellschaft, Partnerschaftsgesellschaft"
        },
        {
          "id": "rf04",
          "front": "Nenne alle Kapitalgesellschaften.",
          "back": "GmbH (inkl. UG haftungsbeschränkt), AG, KGaA"
        },
        {
          "id": "rf05",
          "front": "Einzelunternehmung: Haftung?",
          "back": "Unbeschränkt — mit dem gesamten Privat- und Betriebsvermögen."
        },
        {
          "id": "rf06",
          "front": "Einzelunternehmung: Mindestkapital?",
          "back": "Kein Mindestkapital erforderlich."
        },
        {
          "id": "rf07",
          "front": "Einzelunternehmung: Gewinnverteilung?",
          "back": "Der gesamte Gewinn steht dem Inhaber alleine zu."
        },
        {
          "id": "rf08",
          "front": "Was ist eine GbR?",
          "back": "Gesellschaft bürgerlichen Rechts — vertraglicher Zusammenschluss (auch konkludent möglich) zur Förderung eines gemeinsamen Zwecks. Keine Eintragung ins Handelsregister, keine Firma."
        },
        {
          "id": "rf09",
          "front": "GbR: Haftung?",
          "back": "Alle Gesellschafter haften persönlich und unbeschränkt mit ihrem gesamten Privatvermögen — auch noch 5 Jahre nach Ausstieg."
        },
        {
          "id": "rf10",
          "front": "GbR: Gewinnverteilung?",
          "back": "Gleiche Gewinnaufteilung unter den Gesellschaftern (§ 722 Abs. 1 BGB), sofern nicht anders vereinbart."
        },
        {
          "id": "rf11",
          "front": "Wann wird eine GbR automatisch zur OHG?",
          "back": "Wenn die GbR als Handelsgewerbe geführt wird und die Bilanzierungsgrenzen überschreitet (30.000 € Gewinn oder 350.000 € Umsatz)."
        },
        {
          "id": "rf12",
          "front": "Was ist eine OHG?",
          "back": "Offene Handelsgesellschaft — mindestens 2 Gesellschafter, Eintragung ins Handelsregister zwingend. Nur von Vollkaufleuten wählbar."
        },
        {
          "id": "rf13",
          "front": "OHG: Haftung?",
          "back": "Unbeschränkt, solidarisch — jeder Gesellschafter haftet mit seinem gesamten Privat- und Betriebsvermögen. Keine Einrede zur Teilung."
        },
        {
          "id": "rf14",
          "front": "Was bedeutet Solidarhaftung?",
          "back": "Jeder Gesellschafter haftet voll für alle Verbindlichkeiten der Gesellschaft, auch wenn sie von anderen Gesellschaftern eingegangen wurden. Gläubiger können jeden einzelnen direkt in Anspruch nehmen."
        },
        {
          "id": "rf15",
          "front": "OHG: Gewinnverteilung (gesetzlich)?",
          "back": "Einlagen werden mit 4% verzinst (sofern Gewinn ausreicht), der Rest wird nach Köpfen verteilt — sofern der Gesellschaftsvertrag nichts anderes regelt."
        },
        {
          "id": "rf16",
          "front": "Was ist eine KG?",
          "back": "Kommanditgesellschaft — Personengesellschaft mit zwei Arten von Gesellschaftern: Komplementäre (Vollhafter) und Kommanditisten (Teilhafter)."
        },
        {
          "id": "rf17",
          "front": "KG: Wer ist der Komplementär und wie haftet er?",
          "back": "Der Komplementär (Vollhafter) führt die Geschäfte und haftet unbeschränkt mit seinem gesamten Privatvermögen."
        },
        {
          "id": "rf18",
          "front": "KG: Wer ist der Kommanditist und wie haftet er?",
          "back": "Der Kommanditist haftet nur bis zur Höhe seiner Einlage. Wurde die Einlage durch Verluste gemindert, muss er sie durch Gewinne wieder auffüllen bevor er sich Gewinne auszahlen lassen kann."
        },
        {
          "id": "rf19",
          "front": "KG: Was passiert wenn der einzige Kommanditist ausscheidet?",
          "back": "Verbleiben mehrere Gesellschafter → wird automatisch zur OHG. Verbleibt nur ein Komplementär → wird zur Einzelgesellschaft."
        },
        {
          "id": "rf20",
          "front": "KG: Gewinnverteilung (gesetzlich)?",
          "back": "4% auf den Kapitalanteil, der Rest in einem „angemessenen Verhältnis\" (§§ 167-169 HGB)."
        },
        {
          "id": "rf21",
          "front": "Was ist eine Stille Gesellschaft?",
          "back": "Eine reine Innengesellschaft — ein stiller Gesellschafter beteiligt sich mit einer Einlage am Handelsgewerbe eines anderen. Tritt nach außen nicht in Erscheinung. Kein Handelsregistereintrag."
        },
        {
          "id": "rf22",
          "front": "Was ist eine atypische Stille Gesellschaft?",
          "back": "Eine Stille Gesellschaft, bei der die Verlustbeteiligung für den stillen Gesellschafter vertraglich ausgeschlossen ist. Dann hat er im Konkursfall Anspruch auf Rückgewährung der Einlage."
        },
        {
          "id": "rf23",
          "front": "Was ist eine Partnerschaftsgesellschaft?",
          "back": "Gesellschaftsform ausschließlich für Freiberufler (PartGG seit 1.7.1995). 'Freiberufliche Schwester der OHG'. Unbeschränkte, solidarische Haftung (Ausnahme: bei klar abgrenzbarer persönlicher Auftragsbearbeitung haftet nur der beauftragte Partner). Eintragung ins Partnerschaftsregister."
        },
        {
          "id": "rf24",
          "front": "Was ist die PartGmbB?",
          "back": "Partnerschaftsgesellschaft mit beschränkter Berufshaftung (seit 2013). Berufliche Fehler werden nur mit dem Gesellschaftsvermögen gehaftet, nicht mit dem Privatvermögen. Kürzel 'mbB' im Partnerschaftsregister."
        },
        {
          "id": "rf25",
          "front": "GmbH: Mindestkapital?",
          "back": "25.000 € Stammkapital. Seit 2008 alternativ: UG (haftungsbeschränkt) ab 1 € möglich."
        },
        {
          "id": "rf26",
          "front": "GmbH: Haftung?",
          "back": "Beschränkt — nur das Gesellschaftsvermögen (Stammkapital) haftet. Achtung: Strenge Geschäftsführerhaftung bei verspäteter Insolvenzanmeldung (§ 64 GmbHG)."
        },
        {
          "id": "rf27",
          "front": "GmbH: Organe?",
          "back": "1. Gesellschafterversammlung\n2. Geschäftsführer (von Gesellschafterversammlung gewählt)\n3. Aufsichtsrat (zwingend ab > 500 Arbeitnehmer)"
        },
        {
          "id": "rf28",
          "front": "GmbH: Gewinnverteilung?",
          "back": "Im prozentualen Verhältnis der Gesellschaftsanteile. Gewinn kann auf Beschluss der Gesellschafterversammlung thesauriert werden."
        },
        {
          "id": "rf29",
          "front": "Was ist die UG (haftungsbeschränkt)?",
          "back": "Die 'Mini-GmbH' seit 2008 (MoMiG). Stammkapital ab 1 € möglich. Pflicht: 25% des Jahresgewinns als Rücklage bis 25.000 € erreicht sind. Zwingender Rechtsformzusatz: 'UG (haftungsbeschränkt)'."
        },
        {
          "id": "rf30",
          "front": "AG: Mindestkapital?",
          "back": "50.000 € Grundkapital, zerlegt in Aktien."
        },
        {
          "id": "rf31",
          "front": "AG: Haftung?",
          "back": "Nur mit dem Gesellschaftsvermögen. Aktionäre haften nicht persönlich."
        },
        {
          "id": "rf32",
          "front": "AG: Organe?",
          "back": "1. Vorstand (Geschäftsführung)\n2. Aufsichtsrat (Überwachung, bestellt Vorstand)\n3. Hauptversammlung (alle Aktionäre, wählt Aktionärsvertreter im AR, mind. 1× pro Jahr)"
        },
        {
          "id": "rf33",
          "front": "AG: Aufsichtsrat-Zusammensetzung bei < 500 Mitarbeitern?",
          "back": "Nur Vertreter der Anteilseigner (Aktionäre), keine Arbeitnehmervertreter."
        },
        {
          "id": "rf34",
          "front": "AG: Aufsichtsrat-Zusammensetzung bei > 500 Mitarbeitern?",
          "back": "⅔ Anteilseigner, ⅓ Arbeitnehmer (Drittelbeteiligungsgesetz seit 2004)."
        },
        {
          "id": "rf35",
          "front": "AG: Aufsichtsrat-Zusammensetzung bei > 2.000 Mitarbeitern?",
          "back": "Paritätisch: je ½ Anteilseigner und ½ Arbeitnehmer (inkl. Gewerkschaftsvertreter) nach dem Mitbestimmungsgesetz von 1976."
        },
        {
          "id": "rf36",
          "front": "Welche Besonderheit hat die AG gegenüber allen anderen Rechtsformen?",
          "back": "Sie ist die einzige Gesellschaftsform mit Zugang zum geregelten Eigenkapitalmarkt (Börse)."
        },
        {
          "id": "rf37",
          "front": "Was ist eine Kleine AG?",
          "back": "Seit 1994 ist die Ein-Mann-AG möglich (vorher mind. 5 Gründer). Ziel: AG auch für mittelständische Unternehmen attraktiv machen (z.B. für Generationswechsel)."
        },
        {
          "id": "rf38",
          "front": "Was ist eine GmbH & Co. KG?",
          "back": "Eine KG, deren einziger Komplementär (Vollhafter) eine GmbH ist. Ergebnis: Faktisch beschränkte Haftung aller Beteiligten — die natürlichen Personen sind nur Kommanditisten."
        },
        {
          "id": "rf39",
          "front": "Vergleiche: Einzelunternehmung vs. GbR vs. OHG",
          "back": "Einzelunternehmung: 1 Person, formlos, kein HR nötig.\nGbR: ≥ 2 Personen, formlos, kein HR, keine Kaufmannseigenschaft.\nOHG: ≥ 2 Vollkaufleute, HR-Eintrag zwingend, höheres Ansehen bei Banken."
        },
        {
          "id": "rf40",
          "front": "Welche Rechtsformen erfordern eine Eintragung ins Handelsregister?",
          "back": "OHG, KG, GmbH, UG, AG, KGaA (= alle außer GbR, Stille Gesellschaft und Einzelunternehmung bei Kleingewerbe). Partnerschaftsgesellschaft → eigenes Partnerschaftsregister."
        },
        {
          "id": "rf41",
          "front": "Welche Rechtsformen haben KEIN Mindestkapital?",
          "back": "Einzelunternehmung, GbR, OHG, KG, Stille Gesellschaft, Partnerschaftsgesellschaft. Die UG hat formal 1 € Minimum."
        },
        {
          "id": "rf42",
          "front": "Was ist eine juristische Person?",
          "back": "Eine Gesellschaft mit eigener Rechtspersönlichkeit. Sie ist rechts- aber nicht geschäftsfähig — sie kann Vermögen haben, klagen und verklagt werden, handelt aber durch ihre Organe (Geschäftsführer, Vorstand, etc.)."
        }
      ]
    },
    {
      "title": "Unternehmensverbund",
      "location": "Satz 1, S. 159",
      "notes": "",
      "attachments": [
        {
          "id": "a9kbjpio5dpw",
          "name": "Anteilshaltung_in_Unternehmen.m4a",
          "path": "notes/Anteilshaltung_in_Unternehmen.m4a",
          "source": "repo"
        }
      ],
      "id": "4a9xz22h3rto",
      "cards": []
    },
    {
      "title": "Due Diligence",
      "location": "Satz 1, S. 166",
      "notes": "",
      "attachments": [
        {
          "id": "j6f7kp5d4dzd",
          "name": "Due Diligence erklärt.m4a",
          "path": "notes/Due Diligence erklärt.m4a",
          "source": "repo"
        }
      ],
      "id": "wpo1gav23rto",
      "cards": []
    },
    {
      "title": "Standardmodell Management",
      "location": "Satz 2, S. 10",
      "notes": "",
      "attachments": [],
      "id": "axftssp23rto",
      "cards": []
    },
    {
      "title": "Portfoliomethodik / BCG-Matrix",
      "location": "Satz 2, S. 46",
      "notes": "",
      "attachments": [],
      "id": "jmy4y2j23rto",
      "cards": []
    },
    {
      "title": "Kennziffern / Bilanzanalyse",
      "location": "Satz 2, S. 95",
      "notes": "",
      "attachments": [
        {
          "id": "wbtgkb2k7msf",
          "name": "Bilanzanalyse_Lernzettel.pdf",
          "path": "notes/Bilanzanalyse_Lernzettel.pdf",
          "source": "repo"
        }
      ],
      "id": "z7qnxu0n3rto",
      "cards": []
    },
    {
      "title": "Balanced Scorecard",
      "location": "Satz 2, S. 87",
      "notes": "",
      "attachments": [],
      "id": "bd90u8is3rto",
      "cards": []
    },
    {
      "title": "XY Theory",
      "location": "Satz 2, S. 177",
      "notes": "",
      "attachments": [],
      "id": "lnwrrgeu3rto",
      "cards": []
    },
    {
      "title": "Blue Ocean",
      "location": "Separate Datei in Moodle",
      "notes": "",
      "attachments": [
        {
          "id": "12cd8hx15bs0",
          "name": "Blue Ocean.pdf",
          "path": "materialien/Blue Ocean.pdf",
          "source": "repo"
        }
      ],
      "id": "j2jbktkc3rto",
      "cards": []
    },
    {
      "title": "Herzberg + Maslow",
      "location": "Satz 2, S. 112",
      "notes": "",
      "attachments": [],
      "id": "typl0gob3rto",
      "cards": []
    },
    {
      "id": "zoxu21n194er",
      "title": "Unternehmenssteuern",
      "location": "aus der Vorlesung",
      "notes": "Ertragsteuern = KSt + SolZ + GewSt\nKSt   = Gewinn × 15 %\nSolZ  = KSt × 5,5 %\n      = Gewinn × 0,825 %\nGewSt = Gewerbeertrag × 3,5 % × Hebesatz",
      "attachments": [
        {
          "id": "crlg1nxysooa",
          "name": "Unternehmenssteuern_Lernblatt.html",
          "path": "notes/Unternehmenssteuern_Lernblatt.html",
          "source": "repo"
        },
        {
          "id": "fxbpwsu00zz3",
          "name": "Unternehmenssteuern_Lernblatt.pdf",
          "path": "notes/Unternehmenssteuern_Lernblatt.pdf",
          "source": "repo"
        }
      ],
      "notesHeight": "102px",
      "cards": []
    }
  ],
  "ludolph": [
    {
      "id": "u1vrzj8y8h49",
      "text": "Im Durchschnitt war der Graben nur ein Meter tief und trotzdem ist die Kuh ersoffen.",
      "height": "55px"
    },
    {
      "id": "wn02mkpdtq0t",
      "text": "Immer viel trinken, aber von Wasser ist nicht die Rede!",
      "height": "55px"
    },
    {
      "id": "eml4ppjlu85h",
      "text": "Die Hälfte der Deutschen können keine Bruchrechnung, das sind schonmal 30%.",
      "height": "55px"
    },
    {
      "id": "h5wft6cybnvw",
      "text": "Die Basis ist die Grundlage aller Fundamente.",
      "height": "55px"
    },
    {
      "id": "ifv0a7nxcai3",
      "text": "Planung ist, den Zufall durch den Irrtum zu ersetzen.",
      "height": "2px"
    },
    {
      "id": "0l88j186d1sk",
      "text": "60%??? So viele sind wird doch garnicht !!",
      "height": "32px"
    },
    {
      "id": "08uu4pqddj93",
      "text": "Viel schlimmer als eine Bank auszurauben ist es, eine Bank zu gründen.",
      "height": "55px"
    },
    {
      "id": "hnzdeio3h184",
      "text": "Der Mehrwert ist der Wert, der mehr wert ist als der Wert wert ist.",
      "height": "63px"
    },
    {
      "id": "dgd6x4ef710x",
      "text": "Management ist ein totes Pferd.",
      "height": "2px"
    }
  ],
  "_meta": {
    "lastSaved": "2026-06-02T16:11:08.406Z"
  }
};
