// Auto-generated by index.html – nicht von Hand editieren.
window.KLAUSUR_DATA = {
  "topics": [
    {
      "title": "A short Time Travel",
      "location": "Satz 1, S. 43",
      "notes": "",
      "attachments": [
        {
          "id": "kge0058i52uv",
          "name": "A_short_time_travel_-_überblick.m4a",
          "path": "notes/A_short_time_travel_-_überblick.m4a",
          "source": "repo"
        }
      ],
      "id": "u3cjti8e3rto"
    },
    {
      "title": "SWOT-Analyse",
      "location": "Satz 1, S. 86",
      "notes": "",
      "attachments": [
        {
          "id": "4eols6ix4jav",
          "name": "SWOT-Analyse erklärt.m4a",
          "path": "notes/SWOT-Analyse erklärt.m4a",
          "source": "repo"
        }
      ],
      "id": "imc4ee9j3rto"
    },
    {
      "title": "Nutzwertanalyse",
      "location": "Satz 1, S. 99",
      "notes": "",
      "attachments": [
        {
          "id": "6uzpehsaxt16",
          "name": "Nutzwertanalyse erklärt.m4a",
          "path": "notes/Nutzwertanalyse erklärt.m4a",
          "source": "repo"
        }
      ],
      "id": "jsgiw7sz3rto"
    },
    {
      "title": "Rechtsformen",
      "location": "Satz 1, S. 109",
      "notes": "",
      "attachments": [],
      "id": "cijrjc8g3rto"
    },
    {
      "title": "Unternehmensverbund",
      "location": "Satz 1, S. 159",
      "notes": "",
      "attachments": [
        {
          "id": "a9kbjpio5dpw",
          "name": "Anteilshaltung_in_Unternehmen.m4a",
          "path": "notes/Anteilshaltung_in_Unternehmen.m4a",
          "source": "repo"
        }
      ],
      "id": "4a9xz22h3rto"
    },
    {
      "title": "Due Diligence",
      "location": "Satz 1, S. 166",
      "notes": "",
      "attachments": [
        {
          "id": "j6f7kp5d4dzd",
          "name": "Due Diligence erklärt.m4a",
          "path": "notes/Due Diligence erklärt.m4a",
          "source": "repo"
        }
      ],
      "id": "wpo1gav23rto"
    },
    {
      "title": "Standardmodell Management",
      "location": "Satz 2, S. 10",
      "notes": "",
      "attachments": [],
      "id": "axftssp23rto"
    },
    {
      "title": "Portfoliomethodik / BCG-Matrix",
      "location": "Satz 2, S. 46",
      "notes": "",
      "attachments": [],
      "id": "jmy4y2j23rto"
    },
    {
      "title": "Kennziffern / Bilanzanalyse",
      "location": "Satz 2, S. 95",
      "notes": "",
      "attachments": [
        {
          "id": "wbtgkb2k7msf",
          "name": "Bilanzanalyse_Lernzettel.pdf",
          "path": "notes/Bilanzanalyse_Lernzettel.pdf",
          "source": "repo"
        }
      ],
      "id": "z7qnxu0n3rto"
    },
    {
      "title": "Balanced Scorecard",
      "location": "Satz 2, S. 87",
      "notes": "",
      "attachments": [],
      "id": "bd90u8is3rto"
    },
    {
      "title": "XY Theory",
      "location": "Satz 2, S. 177",
      "notes": "",
      "attachments": [],
      "id": "lnwrrgeu3rto"
    },
    {
      "title": "Blue Ocean",
      "location": "Separate Datei in Moodle",
      "notes": "",
      "attachments": [
        {
          "id": "12cd8hx15bs0",
          "name": "Blue Ocean.pdf",
          "path": "materialien/Blue Ocean.pdf",
          "source": "repo"
        }
      ],
      "id": "j2jbktkc3rto"
    },
    {
      "title": "Herzberg + Maslow",
      "location": "Satz 2, S. 112",
      "notes": "",
      "attachments": [],
      "id": "typl0gob3rto"
    },
    {
      "id": "zoxu21n194er",
      "title": "Unternehmenssteuern",
      "location": "aus der Vorlesung",
      "notes": "Ertragsteuern = KSt + SolZ + GewSt\nKSt   = Gewinn × 15 %\nSolZ  = KSt × 5,5 %\n      = Gewinn × 0,825 %\nGewSt = Gewerbeertrag × 3,5 % × Hebesatz",
      "attachments": [
        {
          "id": "crlg1nxysooa",
          "name": "Unternehmenssteuern_Lernblatt.html",
          "path": "notes/Unternehmenssteuern_Lernblatt.html",
          "source": "repo"
        },
        {
          "id": "fxbpwsu00zz3",
          "name": "Unternehmenssteuern_Lernblatt.pdf",
          "path": "notes/Unternehmenssteuern_Lernblatt.pdf",
          "source": "repo"
        }
      ],
      "notesHeight": "102px"
    }
  ],
  "ludolph": [
    {
      "id": "u1vrzj8y8h49",
      "text": "Im Durchschnitt war der graben nur ein Meter tief und trotzdem ist die Kuh ersoffen \n",
      "height": "60px"
    },
    {
      "id": "wn02mkpdtq0t",
      "text": "Immer viel trinken, aber von Wasser ist nicht die Rede"
    },
    {
      "id": "eml4ppjlu85h",
      "text": "Die Hälfte der deutschen können keine Bruchrechnung, das sind schonmal 30 %",
      "height": "58px"
    },
    {
      "id": "h5wft6cybnvw",
      "text": "Die Basis ist die Grundlage aller Fundamente"
    },
    {
      "id": "ifv0a7nxcai3",
      "text": "Planung ist den Zufall durch den Irrtum zu ersetzen"
    },
    {
      "id": "0l88j186d1sk",
      "text": "60%??? So viele sind wird doch garnicht !!",
      "height": "32px"
    },
    {
      "id": "08uu4pqddj93",
      "text": "Viel schlimmer als eine Bank auszurauben ist es eine Bank zu gründen ",
      "height": "61px"
    },
    {
      "id": "hnzdeio3h184",
      "text": "Der Mehrwert ist der Wert, der mehr wert ist als der Wert wert groß ist",
      "height": "63px"
    }
  ],
  "_meta": {
    "lastSaved": "2026-06-02T11:44:54.258Z"
  }
};
