// GET  /api/data  → { state, sha }
// POST /api/data  body: { state, expectedSha, fileShas: [{path, sha}] }
//                  → { sha } after creating one atomic commit

const gh = require("./_github.js");

const DATA_FILENAME = "klausur-data.js";
const DEFAULTS = {
  topics: [
    { title: "A short Time Travel",         location: "Satz 1, S. 43",   notes: "", attachments: [] },
    { title: "SWOT-Analyse",                 location: "Satz 1, S. 86",   notes: "", attachments: [] },
    { title: "Nutzwertanalyse",              location: "Satz 1, S. 99",   notes: "", attachments: [] },
    { title: "Rechtsformen",                 location: "Satz 1, S. 109",  notes: "", attachments: [] },
    { title: "Unternehmensverbund",          location: "Satz 1, S. 159",  notes: "", attachments: [] },
    { title: "Due Diligence",                location: "Satz 1, S. 166",  notes: "", attachments: [] },
    { title: "Standardmodell Management",    location: "Satz 2, S. 10",   notes: "", attachments: [] },
    { title: "Portfoliomethodik",            location: "Satz 2, S. 46",   notes: "", attachments: [] },
    { title: "Kennziffern / Bilanzanalyse",  location: "Satz 2, S. 95",   notes: "", attachments: [] },
    { title: "Balanced Scorecard",           location: "Satz 2, S. 87",   notes: "", attachments: [] },
    { title: "XY Theory",                    location: "Satz 2, S. 177",  notes: "", attachments: [] },
    { title: "Blue Ocean",                   location: "Separate Datei",  notes: "", attachments: [] },
    { title: "Herzberg + Maslow",            location: "Satz 2, S. 112",  notes: "", attachments: [] }
  ],
  ludolph: [],
  deletedCards: []
};

function utf8ToB64(str) { return Buffer.from(str, "utf8").toString("base64"); }
function b64ToUtf8(b64)  { return Buffer.from(b64, "base64").toString("utf8"); }

function parseDataFile(text) {
  const m = text.match(/window\.KLAUSUR_DATA\s*=\s*([\s\S]+?);\s*$/);
  if (!m) throw new Error(`${DATA_FILENAME} format unexpected`);
  return JSON.parse(m[1]);
}

function buildDataFile(state) {
  const dump = {
    topics: state.topics,
    ludolph: state.ludolph,
    deletedCards: Array.isArray(state.deletedCards) ? state.deletedCards : [],
    _meta: { lastSaved: new Date().toISOString() }
  };
  return "// Auto-generated by index.html – nicht von Hand editieren.\n"
       + "window.KLAUSUR_DATA = " + JSON.stringify(dump, null, 2) + ";\n";
}

module.exports = async (req, res) => {
  try {
    if (req.method === "GET") {
      const sha = await gh.getRefSha();
      const c = await gh.getContent(DATA_FILENAME);
      let state;
      if (!c) state = DEFAULTS;
      else {
        let text;
        if (c.content) text = b64ToUtf8(c.content);
        else {
          const blob = await gh.getBlob(c.sha);
          text = b64ToUtf8(blob.content);
        }
        state = parseDataFile(text);
      }
      return gh.sendJson(res, 200, { state, sha });
    }

    if (req.method === "POST") {
      const body = await gh.readJson(req);
      const { state, expectedSha, fileShas = [] } = body;
      if (!state || !Array.isArray(state.topics)) {
        return gh.sendJson(res, 400, { error: "Invalid state payload" });
      }

      // Conflict check: someone else committed between load and save
      const currentSha = await gh.getRefSha();
      if (expectedSha && currentSha !== expectedSha) {
        return gh.sendJson(res, 409, {
          error: "Repo wurde inzwischen geändert. Bitte ↻ Neu laden und nochmal speichern."
        });
      }

      const baseCommit = await gh.getCommit(currentSha);
      const baseTreeSha = baseCommit.tree.sha;

      // Always update the data file
      const dataBlob = await gh.createBlob(utf8ToB64(buildDataFile(state)));
      const treeEntries = [{ path: DATA_FILENAME, mode: "100644", type: "blob", sha: dataBlob.sha }];

      // Add any pre-uploaded files (their blob SHAs already exist on GitHub)
      for (const f of fileShas) {
        if (!f || !f.path || !f.sha) continue;
        treeEntries.push({ path: f.path, mode: "100644", type: "blob", sha: f.sha });
      }

      const tree = await gh.createTree(baseTreeSha, treeEntries);
      const totalChanges = treeEntries.length;
      const message = fileShas.length
        ? `Klausur-App: ${DATA_FILENAME} + ${fileShas.length} Anhang(e)`
        : `Klausur-App: ${DATA_FILENAME} aktualisiert`;
      const commit = await gh.createCommit(message, tree.sha, currentSha);
      await gh.updateRef(commit.sha);

      return gh.sendJson(res, 200, { sha: commit.sha, changes: totalChanges });
    }

    res.setHeader("Allow", "GET, POST");
    return gh.sendJson(res, 405, { error: "Method not allowed" });
  } catch (e) {
    return gh.sendError(res, e);
  }
};
